package com.msmith.rpgai.observables;

import android.util.Log;

/**
 * TODO: Insert description here. (generated by smithmi)
 */
public class Foo {
  public void foo(MutableCollection<MutableValue<Integer>> list) {
    //ImmutableCollection<MutableValue<Integer>> immutableList = list;
    ImmutableCollection<ImmutableValue<Integer>> reallyImmutableList = ImmutableCollections.cast(list);
    Log.d("Foo", "list = " + reallyImmutableList);
  }
}
