package com.msmith.rpgai.observables;

/**
 * TODO: Insert description here. (generated by smithmi)
 */
public class ImmutableCollections {

  public static <T, U extends T> ImmutableCollection<T> cast(ImmutableCollection<U> collection) {

    @SuppressWarnings("unchecked")
    ImmutableCollection<T> immutableCollection = (ImmutableCollection<T>)collection;

    return immutableCollection;
  }

}
